/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user account.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login and get access/refresh tokens.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Refresh access token using refresh token.
         */
        post: operations["refresh_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get current user information.
         */
        get: operations["get_current_user_info_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description List all projects for the current user.
         */
        get: operations["list_projects_api_v1_projects__get"];
        put?: never;
        /**
         * Create Project
         * @description Create a new keyword research project.
         */
        post: operations["create_project_api_v1_projects__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description Get a specific project by ID.
         */
        get: operations["get_project_api_v1_projects__project_id__get"];
        /**
         * Update Project
         * @description Update a project.
         */
        put: operations["update_project_api_v1_projects__project_id__put"];
        post?: never;
        /**
         * Delete Project
         * @description Delete a project.
         */
        delete: operations["delete_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipeline/{project_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Pipeline
         * @description Start a new pipeline run for a project.
         */
        post: operations["start_pipeline_api_v1_pipeline__project_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipeline/{project_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pipeline Runs
         * @description List pipeline runs for a project.
         */
        get: operations["list_pipeline_runs_api_v1_pipeline__project_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipeline/{project_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pipeline Run
         * @description Get a specific pipeline run.
         */
        get: operations["get_pipeline_run_api_v1_pipeline__project_id__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipeline/{project_id}/runs/{run_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pipeline Progress
         * @description Get real-time progress for a pipeline run.
         */
        get: operations["get_pipeline_progress_api_v1_pipeline__project_id__runs__run_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipeline/{project_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Pipeline
         * @description Pause a running pipeline.
         */
        post: operations["pause_pipeline_api_v1_pipeline__project_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipeline/{project_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Pipeline
         * @description Resume a paused pipeline.
         */
        post: operations["resume_pipeline_api_v1_pipeline__project_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keywords/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Keywords
         * @description List keywords for a project with filters.
         */
        get: operations["list_keywords_api_v1_keywords__project_id__get"];
        put?: never;
        /**
         * Create Keyword
         * @description Manually add a keyword to a project.
         */
        post: operations["create_keyword_api_v1_keywords__project_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keywords/{project_id}/{keyword_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Keyword
         * @description Get detailed keyword information.
         */
        get: operations["get_keyword_api_v1_keywords__project_id___keyword_id__get"];
        /**
         * Update Keyword
         * @description Update a keyword.
         */
        put: operations["update_keyword_api_v1_keywords__project_id___keyword_id__put"];
        post?: never;
        /**
         * Delete Keyword
         * @description Delete (exclude) a keyword.
         */
        delete: operations["delete_keyword_api_v1_keywords__project_id___keyword_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keywords/{project_id}/bulk-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Update Keywords
         * @description Bulk update keywords.
         */
        post: operations["bulk_update_keywords_api_v1_keywords__project_id__bulk_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Topics
         * @description List topics for a project.
         */
        get: operations["list_topics_api_v1_topics__project_id__get"];
        put?: never;
        /**
         * Create Topic
         * @description Create a new topic.
         */
        post: operations["create_topic_api_v1_topics__project_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{project_id}/ranked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ranked Topics
         * @description Get prioritized topic backlog.
         */
        get: operations["get_ranked_topics_api_v1_topics__project_id__ranked_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{project_id}/hierarchy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Topic Hierarchy
         * @description Get topic hierarchy tree.
         */
        get: operations["get_topic_hierarchy_api_v1_topics__project_id__hierarchy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{project_id}/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Topic
         * @description Get detailed topic information.
         */
        get: operations["get_topic_api_v1_topics__project_id___topic_id__get"];
        /**
         * Update Topic
         * @description Update a topic.
         */
        put: operations["update_topic_api_v1_topics__project_id___topic_id__put"];
        post?: never;
        /**
         * Delete Topic
         * @description Delete a topic.
         */
        delete: operations["delete_topic_api_v1_topics__project_id___topic_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{project_id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Topics
         * @description Merge multiple topics into one.
         */
        post: operations["merge_topics_api_v1_topics__project_id__merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/{project_id}/briefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Briefs
         * @description List content briefs for a project.
         */
        get: operations["list_briefs_api_v1_content__project_id__briefs_get"];
        put?: never;
        /**
         * Create Brief
         * @description Create a new content brief.
         */
        post: operations["create_brief_api_v1_content__project_id__briefs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/{project_id}/briefs/{brief_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Brief
         * @description Get detailed content brief.
         */
        get: operations["get_brief_api_v1_content__project_id__briefs__brief_id__get"];
        /**
         * Update Brief
         * @description Update a content brief.
         */
        put: operations["update_brief_api_v1_content__project_id__briefs__brief_id__put"];
        post?: never;
        /**
         * Delete Brief
         * @description Delete a content brief.
         */
        delete: operations["delete_brief_api_v1_content__project_id__briefs__brief_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content/{project_id}/briefs/{brief_id}/instructions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Writer Instructions
         * @description Get writer instructions for a brief.
         */
        get: operations["get_writer_instructions_api_v1_content__project_id__briefs__brief_id__instructions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ContentBriefCreate
         * @description Schema for creating a content brief.
         */
        ContentBriefCreate: {
            /** Topic Id */
            topic_id: string;
            /** Primary Keyword */
            primary_keyword: string;
            /** Working Titles */
            working_titles?: string[] | null;
            /** Target Word Count Min */
            target_word_count_min?: number | null;
            /** Target Word Count Max */
            target_word_count_max?: number | null;
        };
        /**
         * ContentBriefDetailResponse
         * @description Detailed content brief response.
         */
        ContentBriefDetailResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Topic Id */
            topic_id: string;
            /** Primary Keyword */
            primary_keyword: string;
            /** Search Intent */
            search_intent: string | null;
            /** Page Type */
            page_type: string | null;
            /** Funnel Stage */
            funnel_stage: string | null;
            /** Working Titles */
            working_titles: string[] | null;
            /** Target Audience */
            target_audience: string | null;
            /** Target Word Count Min */
            target_word_count_min: number | null;
            /** Target Word Count Max */
            target_word_count_max: number | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Reader Job To Be Done */
            reader_job_to_be_done: string | null;
            /** Outline */
            outline: {
                [key: string]: unknown;
            }[] | null;
            /** Supporting Keywords */
            supporting_keywords: string[] | null;
            /** Supporting Keywords Map */
            supporting_keywords_map: {
                [key: string]: unknown;
            } | null;
            /** Examples Required */
            examples_required: string[] | null;
            /** Faq Questions */
            faq_questions: string[] | null;
            /** Recommended Schema Type */
            recommended_schema_type: string | null;
            /** Internal Links Out */
            internal_links_out: {
                [key: string]: unknown;
            }[] | null;
            /** Internal Links In */
            internal_links_in: {
                [key: string]: unknown;
            }[] | null;
            /** Money Page Links */
            money_page_links: {
                [key: string]: unknown;
            }[] | null;
            /** External Sources Required */
            external_sources_required: string[] | null;
            /** Meta Title Guidelines */
            meta_title_guidelines: string | null;
            /** Meta Description Guidelines */
            meta_description_guidelines: string | null;
            /** Must Include Sections */
            must_include_sections: string[] | null;
        };
        /**
         * ContentBriefListResponse
         * @description Schema for content brief list response.
         */
        ContentBriefListResponse: {
            /** Items */
            items: components["schemas"]["ContentBriefResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * ContentBriefResponse
         * @description Schema for content brief response.
         */
        ContentBriefResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Topic Id */
            topic_id: string;
            /** Primary Keyword */
            primary_keyword: string;
            /** Search Intent */
            search_intent: string | null;
            /** Page Type */
            page_type: string | null;
            /** Funnel Stage */
            funnel_stage: string | null;
            /** Working Titles */
            working_titles: string[] | null;
            /** Target Audience */
            target_audience: string | null;
            /** Target Word Count Min */
            target_word_count_min: number | null;
            /** Target Word Count Max */
            target_word_count_max: number | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ContentBriefUpdate
         * @description Schema for updating a content brief.
         */
        ContentBriefUpdate: {
            /** Working Titles */
            working_titles?: string[] | null;
            /** Outline */
            outline?: components["schemas"]["OutlineSection"][] | null;
            /** Supporting Keywords */
            supporting_keywords?: string[] | null;
            /** Faq Questions */
            faq_questions?: string[] | null;
            /** Target Word Count Min */
            target_word_count_min?: number | null;
            /** Target Word Count Max */
            target_word_count_max?: number | null;
            /** Status */
            status?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KeywordBulkUpdateRequest
         * @description Schema for bulk keyword update.
         */
        KeywordBulkUpdateRequest: {
            /** Keyword Ids */
            keyword_ids: string[];
            /** Status */
            status?: string | null;
            /** Intent */
            intent?: string | null;
            /** Topic Id */
            topic_id?: string | null;
        };
        /**
         * KeywordCreate
         * @description Schema for creating a keyword.
         */
        KeywordCreate: {
            /** Keyword */
            keyword: string;
            /**
             * Language
             * @default en
             */
            language: string;
            /**
             * Locale
             * @default en-US
             */
            locale: string;
            /**
             * Source
             * @default manual
             */
            source: string;
        };
        /**
         * KeywordDetailResponse
         * @description Detailed keyword response with all fields.
         */
        KeywordDetailResponse: {
            /** Id */
            id: string;
            /** Keyword */
            keyword: string;
            /** Keyword Normalized */
            keyword_normalized: string;
            /** Language */
            language: string;
            /** Locale */
            locale: string;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Search Volume */
            search_volume: number | null;
            /** Cpc */
            cpc: number | null;
            /** Difficulty */
            difficulty: number | null;
            /** Intent */
            intent: string | null;
            /** Recommended Page Type */
            recommended_page_type: string | null;
            /** Funnel Stage */
            funnel_stage: string | null;
            /** Priority Score */
            priority_score: number | null;
            /** Topic Id */
            topic_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Source Method */
            source_method: string | null;
            /** Raw Variants */
            raw_variants: string[] | null;
            /** Exclusion Flags */
            exclusion_flags: string[] | null;
            /** Competition */
            competition: number | null;
            /** Trend Data */
            trend_data: number[] | null;
            /** Metrics Data Source */
            metrics_data_source: string | null;
            /** Metrics Updated At */
            metrics_updated_at: string | null;
            /** Metrics Confidence */
            metrics_confidence: number | null;
            /** Intent Confidence */
            intent_confidence: number | null;
            /** Page Type Rationale */
            page_type_rationale: string | null;
            /** Risk Flags */
            risk_flags: string[] | null;
            /** Priority Factors */
            priority_factors: {
                [key: string]: unknown;
            } | null;
            /** Serp Top Results */
            serp_top_results: {
                [key: string]: unknown;
            }[] | null;
            /** Serp Features */
            serp_features: string[] | null;
            /** Validated Intent */
            validated_intent: string | null;
            /** Validated Page Type */
            validated_page_type: string | null;
            /** Exclusion Reason */
            exclusion_reason: string | null;
        };
        /**
         * KeywordListResponse
         * @description Schema for keyword list response.
         */
        KeywordListResponse: {
            /** Items */
            items: components["schemas"]["KeywordResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * KeywordResponse
         * @description Schema for keyword response.
         */
        KeywordResponse: {
            /** Id */
            id: string;
            /** Keyword */
            keyword: string;
            /** Keyword Normalized */
            keyword_normalized: string;
            /** Language */
            language: string;
            /** Locale */
            locale: string;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Search Volume */
            search_volume: number | null;
            /** Cpc */
            cpc: number | null;
            /** Difficulty */
            difficulty: number | null;
            /** Intent */
            intent: string | null;
            /** Recommended Page Type */
            recommended_page_type: string | null;
            /** Funnel Stage */
            funnel_stage: string | null;
            /** Priority Score */
            priority_score: number | null;
            /** Topic Id */
            topic_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * KeywordUpdate
         * @description Schema for updating a keyword.
         */
        KeywordUpdate: {
            /** Intent */
            intent?: string | null;
            /** Recommended Page Type */
            recommended_page_type?: string | null;
            /** Status */
            status?: string | null;
            /** Exclusion Reason */
            exclusion_reason?: string | null;
        };
        /**
         * OutlineSection
         * @description Content outline section.
         */
        OutlineSection: {
            /** Heading */
            heading: string;
            /** Level */
            level: number;
            /** Purpose */
            purpose?: string | null;
            /** Key Points */
            key_points?: string[] | null;
            /** Supporting Keywords */
            supporting_keywords?: string[] | null;
        };
        /**
         * PipelineProgressResponse
         * @description Schema for real-time pipeline progress.
         */
        PipelineProgressResponse: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Current Step */
            current_step: number | null;
            /** Current Step Name */
            current_step_name: string | null;
            /** Overall Progress */
            overall_progress: number;
            /** Steps */
            steps: components["schemas"]["StepExecutionResponse"][];
        };
        /**
         * PipelineRunResponse
         * @description Schema for pipeline run response.
         */
        PipelineRunResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Start Step */
            start_step: number | null;
            /** End Step */
            end_step: number | null;
            /** Skip Steps */
            skip_steps: number[] | null;
            /** Step Executions */
            step_executions: components["schemas"]["StepExecutionResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PipelineStartRequest
         * @description Schema for starting a pipeline run.
         */
        PipelineStartRequest: {
            /**
             * Start Step
             * @default 0
             */
            start_step: number;
            /** End Step */
            end_step?: number | null;
            /** Skip Steps */
            skip_steps?: number[] | null;
        };
        /**
         * ProjectConstraints
         * @description Constraints and limitations.
         */
        ProjectConstraints: {
            /**
             * Budget Tier
             * @default medium
             * @enum {string}
             */
            budget_tier: "low" | "medium" | "high";
            /**
             * Content Team Size
             * @default 1
             */
            content_team_size: number;
            /** Max Keywords To Target */
            max_keywords_to_target?: number | null;
            /**
             * Max Difficulty Score
             * @default 70
             */
            max_difficulty_score: number | null;
            /**
             * Min Search Volume
             * @default 10
             */
            min_search_volume: number | null;
            /**
             * Exclude Branded Keywords
             * @default false
             */
            exclude_branded_keywords: boolean;
        };
        /**
         * ProjectCreate
         * @description Schema for creating a new project.
         */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Domain */
            domain: string;
            /** Description */
            description?: string | null;
            /**
             * Primary Language
             * @default en
             */
            primary_language: string;
            /**
             * Primary Locale
             * @default en-US
             */
            primary_locale: string;
            /** Secondary Locales */
            secondary_locales?: string[] | null;
            goals?: components["schemas"]["ProjectGoals"] | null;
            constraints?: components["schemas"]["ProjectConstraints"] | null;
            settings?: components["schemas"]["ProjectSettings"] | null;
        };
        /**
         * ProjectGoals
         * @description Business goals for the keyword research project.
         */
        ProjectGoals: {
            /**
             * Primary Objective
             * @default traffic
             */
            primary_objective: string;
            /** Target Monthly Traffic */
            target_monthly_traffic?: number | null;
            /** Target Conversion Rate */
            target_conversion_rate?: number | null;
            /** Priority Topics */
            priority_topics?: string[] | null;
            /** Excluded Topics */
            excluded_topics?: string[] | null;
        };
        /**
         * ProjectListResponse
         * @description Schema for project list response.
         */
        ProjectListResponse: {
            /** Items */
            items: components["schemas"]["ProjectResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * ProjectResponse
         * @description Schema for project response.
         */
        ProjectResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Domain */
            domain: string;
            /** Description */
            description: string | null;
            /** Primary Language */
            primary_language: string;
            /** Primary Locale */
            primary_locale: string;
            /** Secondary Locales */
            secondary_locales: string[] | null;
            /** Site Maturity */
            site_maturity: string | null;
            /** Primary Goal */
            primary_goal: string | null;
            /** Current Step */
            current_step: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProjectSettings
         * @description Project-specific pipeline settings.
         */
        ProjectSettings: {
            /** Skip Steps */
            skip_steps?: number[];
            /** Step Configs */
            step_configs?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            } | null;
            /** Notification Webhook */
            notification_webhook?: string | null;
            /**
             * Auto Continue On Error
             * @default false
             */
            auto_continue_on_error: boolean;
        };
        /**
         * ProjectUpdate
         * @description Schema for updating a project.
         */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Primary Language */
            primary_language?: string | null;
            /** Primary Locale */
            primary_locale?: string | null;
            /** Secondary Locales */
            secondary_locales?: string[] | null;
            goals?: components["schemas"]["ProjectGoals"] | null;
            constraints?: components["schemas"]["ProjectConstraints"] | null;
            settings?: components["schemas"]["ProjectSettings"] | null;
        };
        /**
         * StepExecutionResponse
         * @description Schema for step execution response.
         */
        StepExecutionResponse: {
            /** Id */
            id: string;
            /** Step Number */
            step_number: number;
            /** Step Name */
            step_name: string;
            /** Status */
            status: string;
            /** Progress Percent */
            progress_percent: number;
            /** Progress Message */
            progress_message: string | null;
            /** Items Processed */
            items_processed: number;
            /** Items Total */
            items_total: number | null;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Error Message */
            error_message: string | null;
        };
        /**
         * Token
         * @description Schema for JWT token response.
         */
        Token: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * TokenRefresh
         * @description Schema for token refresh request.
         */
        TokenRefresh: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * TopicCreate
         * @description Schema for creating a topic.
         */
        TopicCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Parent Topic Id */
            parent_topic_id?: string | null;
        };
        /**
         * TopicDetailResponse
         * @description Detailed topic response.
         */
        TopicDetailResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Parent Topic Id */
            parent_topic_id: string | null;
            /** Cluster Method */
            cluster_method: string | null;
            /** Cluster Coherence */
            cluster_coherence: number | null;
            /** Primary Keyword Id */
            primary_keyword_id: string | null;
            /** Dominant Intent */
            dominant_intent: string | null;
            /** Dominant Page Type */
            dominant_page_type: string | null;
            /** Funnel Stage */
            funnel_stage: string | null;
            /** Total Volume */
            total_volume: number | null;
            /** Avg Difficulty */
            avg_difficulty: number | null;
            /** Keyword Count */
            keyword_count: number;
            /** Priority Rank */
            priority_rank: number | null;
            /** Priority Score */
            priority_score: number | null;
            /** Expected Role */
            expected_role: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Priority Factors */
            priority_factors: {
                [key: string]: unknown;
            } | null;
            /** Recommended Url Type */
            recommended_url_type: string | null;
            /** Recommended Publish Order */
            recommended_publish_order: number | null;
            /** Target Money Pages */
            target_money_pages: string[] | null;
            /** Cannibalization Risk */
            cannibalization_risk: number | null;
            /** Overlapping Topic Ids */
            overlapping_topic_ids: string[] | null;
            /** Cluster Notes */
            cluster_notes: string | null;
        };
        /**
         * TopicHierarchyResponse
         * @description Schema for topic hierarchy response.
         */
        TopicHierarchyResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Keyword Count */
            keyword_count: number;
            /** Priority Rank */
            priority_rank: number | null;
            /** Children */
            children: components["schemas"]["TopicHierarchyResponse"][];
        };
        /**
         * TopicListResponse
         * @description Schema for topic list response.
         */
        TopicListResponse: {
            /** Items */
            items: components["schemas"]["TopicResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * TopicMergeRequest
         * @description Schema for merging topics.
         */
        TopicMergeRequest: {
            /** Source Topic Ids */
            source_topic_ids: string[];
            /** Target Name */
            target_name: string;
            /** Target Description */
            target_description?: string | null;
        };
        /**
         * TopicResponse
         * @description Schema for topic response.
         */
        TopicResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Parent Topic Id */
            parent_topic_id: string | null;
            /** Cluster Method */
            cluster_method: string | null;
            /** Cluster Coherence */
            cluster_coherence: number | null;
            /** Primary Keyword Id */
            primary_keyword_id: string | null;
            /** Dominant Intent */
            dominant_intent: string | null;
            /** Dominant Page Type */
            dominant_page_type: string | null;
            /** Funnel Stage */
            funnel_stage: string | null;
            /** Total Volume */
            total_volume: number | null;
            /** Avg Difficulty */
            avg_difficulty: number | null;
            /** Keyword Count */
            keyword_count: number;
            /** Priority Rank */
            priority_rank: number | null;
            /** Priority Score */
            priority_score: number | null;
            /** Expected Role */
            expected_role: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TopicUpdate
         * @description Schema for updating a topic.
         */
        TopicUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Parent Topic Id */
            parent_topic_id?: string | null;
            /** Priority Rank */
            priority_rank?: number | null;
        };
        /**
         * UserCreate
         * @description Schema for user registration.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name?: string | null;
        };
        /**
         * UserLogin
         * @description Schema for user login.
         */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserResponse
         * @description Schema for user response.
         */
        UserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string | null;
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WriterInstructionsResponse
         * @description Schema for writer instructions response.
         */
        WriterInstructionsResponse: {
            /** Id */
            id: string;
            /** Brief Id */
            brief_id: string;
            /** Voice Tone Constraints */
            voice_tone_constraints: {
                [key: string]: unknown;
            } | null;
            /** Forbidden Claims */
            forbidden_claims: string[] | null;
            /** Compliance Notes */
            compliance_notes: string[] | null;
            /** Formatting Requirements */
            formatting_requirements: {
                [key: string]: unknown;
            } | null;
            /** H1 H2 Usage */
            h1_h2_usage: {
                [key: string]: unknown;
            } | null;
            /** Internal Linking Minimums */
            internal_linking_minimums: {
                [key: string]: unknown;
            } | null;
            /** Schema Guidance */
            schema_guidance: string | null;
            /** Qa Checklist */
            qa_checklist: {
                [key: string]: unknown;
            }[] | null;
            /** Pass Fail Thresholds */
            pass_fail_thresholds: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_projects_api_v1_projects__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_pipeline_api_v1_pipeline__project_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pipeline_runs_api_v1_pipeline__project_id__runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pipeline_run_api_v1_pipeline__project_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pipeline_progress_api_v1_pipeline__project_id__runs__run_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_pipeline_api_v1_pipeline__project_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_pipeline_api_v1_pipeline__project_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_keywords_api_v1_keywords__project_id__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                intent?: string | null;
                status?: string | null;
                topic_id?: string | null;
                min_volume?: number | null;
                max_difficulty?: number | null;
                search?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_keyword_api_v1_keywords__project_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeywordCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_keyword_api_v1_keywords__project_id___keyword_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                keyword_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_keyword_api_v1_keywords__project_id___keyword_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                keyword_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeywordUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_keyword_api_v1_keywords__project_id___keyword_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                keyword_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_keywords_api_v1_keywords__project_id__bulk_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeywordBulkUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_topics_api_v1_topics__project_id__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_topic_api_v1_topics__project_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ranked_topics_api_v1_topics__project_id__ranked_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topic_hierarchy_api_v1_topics__project_id__hierarchy_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicHierarchyResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_topic_api_v1_topics__project_id___topic_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_topic_api_v1_topics__project_id___topic_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_topic_api_v1_topics__project_id___topic_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_topics_api_v1_topics__project_id__merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicMergeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_briefs_api_v1_content__project_id__briefs_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentBriefListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_brief_api_v1_content__project_id__briefs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentBriefCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentBriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brief_api_v1_content__project_id__briefs__brief_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                brief_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentBriefDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_brief_api_v1_content__project_id__briefs__brief_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                brief_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentBriefUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentBriefResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_brief_api_v1_content__project_id__briefs__brief_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                brief_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_writer_instructions_api_v1_content__project_id__briefs__brief_id__instructions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                brief_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriterInstructionsResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
